In [2]:
import numpy as np

In [3]:
# for testing result
"""input_img = np.array([[[ 1,  2 ,  3.],
        [4.,  5., 6.],
        [ 7.,  8.,  9.]],

       [[11., 22.,  33.],
        [44., 55., 66.],
        [ 77.,  88., 99.]]])
input_filter = np.array([[[ 1,  2 ],
        [4.,  5.]],

       [[2, 1],
        [4., 5]]]) """
# output should be
#  [[[ 471.  615.]
 # [ 903. 1047.]]]


# k_dim is filter dimension
def convolution_operation(img_dim=4,k_dim=3,channels=2,padding=False):
    # try to create dynamic padding
    # if k=3 then we need pad_width= 1 to get same dimension output
    # but if k = 5 then we need pad_width=2 to get same dimension output, and so on
    margin_of_zeros = int(k_dim/2)
    # randomly generate img and filter of given size
    input_img=np.random.randn(channels,img_dim,img_dim)
    input_filter=np.random.randn(channels,k_dim,k_dim)


    input_img = np.array([[[ 1,  0 ,  0],
        [1,  1, 0],
        [ 0,  1,  0]],

       [[1, 0,  2],
        [1, 2, 0],
        [ 2,  1, 2]]])
    input_filter = np.array([[[ 0,  0 ],
        [2,  0]],

       [[1, 2],
        [2, 0]]])

    if padding:
        # result dim will be same as img dimension apart from channel
        result_dim = img_dim-k_dim+1+(2*margin_of_zeros)
    else:
        result_dim = img_dim-k_dim+1
    # no of channels is equal to number of filters here we have only one filter that's why
    # result has one channel
    result= np.zeros((1,result_dim,result_dim))
    for channel in range(channels):
        # img per channel
        img = input_img[channel,:,:]
        if padding:
            # i just padded with zeros on length and width
            img = np.pad(img,pad_width=margin_of_zeros)
        # because img and filter should have same no of channels
        k  = input_filter[channel,:,:]
        for i in range(result_dim):
            for j in range(result_dim):
                # crop image and filter should have same size
                crop_img=img[i:k_dim+i,j:k_dim+j]
                sum =0
                for ik in range(crop_img.shape[0]):
                    for jk in range(k_dim):
                        sum+=crop_img[ik,jk]*k[ik,jk]
                result[0,i,j] += sum
    return result

# k usually uneven
#convolution_operation(4,3,padding=False)
convolution_operation(3,2,padding=False)

array([[[ 5., 10.],
        [ 9.,  6.]]])

In [9]:
def pooling(conv_result,kernal_size=2,stride=2):
    # height and width is same in this case
    height = conv_result.shape[1]
    new_height = int(height/stride)
    result_p = np.zeros((1,new_height,new_height))
    for i in range(new_height):
        for j in range(new_height):
            # in crop img we get length and width of matrix
            # kernal is is size of matrix to be croped and stride is moving rate
            # example for k=2,s=2.
            # [0:2,0:2] , [0:2,2:4], [2:4,0:2] , [2:4,2:4],
            crop_img = conv_result[0,i*stride:kernal_size+(i*stride),j*stride:kernal_size+(j*stride)]
            result_p[0,i,j] = np.mean(crop_img)
    return result_p
output= convolution_operation(3,2)
pooling(output,2,2)

array([[[6.5]]])